/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yangyao_android_opencv_OpenCVHelper */

#ifndef _Included_com_example_yangyao_android_opencv_OpenCVHelper
#define _Included_com_example_yangyao_android_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yangyao_android_opencv_OpenCVHelper
 * Method:    crop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_yangyao_android_1opencv_OpenCVHelper_crop
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
